### ISSUE TITLE
Weights of GANs

### ISSUE THREAD

**Issue by AwesomeLemon** [alceubissoto/gan-aug-analysis#1]
Hi,

Your paper is quite interesting. I'm wondering when approximately will you release the weights of the GANs you trained? (the readme says "soon", but it's been 8 months since the last commit)

**Comment by alceubissoto** [comment]
Hi!
Unfortunately, our datacenter had a problem months ago, and the data is still in the process of being recovered. As soon as I get the weights again I can make it available, but I don't know how long will it take :/
I hope the images used for our research, which are available, can help you. Also, if you need any help training the models, I'm happy to help.
